title: Your Site Title
description: >- # this means to ignore newlines until "baseurl:"
  This is my awesome documentation site for my project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yourusername
github_username:  yourusername

# Build settings
markdown: kramdown
# theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-feed
